### ISSUE TITLE
Test Frontend Single article Menu Item

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/GSOC-Webdriver_system_tests_for_CMS#1]
TEST 2.
Steps To be executed:
- Create a Category
- Create an Article which belongs to this category
- Click on Menu Manager, Main Menu
- Add a new Menu Item
- Menu Type Field Choose Article→Single Article
- Go to front end and Verify

**Comment by puneet0191** [comment]
This has been resolved Closing the issue
