### ISSUE TITLE
Test Single Article menu item options

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/GSOC-Webdriver_system_tests_for_CMS#2]
Test all the options available in a menu item and make sure they work ads expected:

![screen shot 2014-05-15 at 13 19 35](https://cloud.githubusercontent.com/assets/1375475/2983380/d649e8b8-dc22-11e3-9117-62d6d286a6e1.png)

**Comment by kshitijSharma2014** [comment]
@javigomez  @puneet0191  @gunjanpatel 
The tests I have written is on the options present in MenuItems and not on the options present in content->article

Which one I have to make? Did I do what you wanted me to do javier or have I done something else?

**Comment by kshitijSharma2014** [comment]
second thing in options Tab in Article Manager when I set 'Show Titlle' to HIDE 
even then it does hide the title on the front end I can see it.

@javigomez  @puneet0191

**Comment by javigomez** [comment]
The options are hierarchical. Always from more general to less general:
- most general: com_content configuration
- next: menu item
- most specific: content article

if you set to HIDE title in **menu item** and SHOW in **article**: title will be shown
if you set to SHOW title in **menu item** and HIDE in **article**: title will be hidden
if you set to SHOW title in **global configuration** and HIDE in **article**: title will be hidden
...
Do I explain what I mean

**Comment by kshitijSharma2014** [comment]
yeah @javigomez  I got your point 
Thank you :)

**Comment by kshitijSharma2014** [comment]
@javigomez 
also I wanted to ask that the test which you wanted me to do, was it the options in menuitems Manager or the article Manager?

**Comment by puneet0191** [comment]
Kshitij can you very what Javi told, and see if we can accommodate tests involving these options

**Comment by kshitijSharma2014** [comment]
@puneet0191  do you mean tests to check the hierarchical order?

Yeah sure!!

**Comment by Bakual** [comment]
Actually, the single article menu item works a bit different. If the menu item matches the article displayed, then the menu item is considered more specific and overrides the article settings.
In all other cases, the article settings override the menu settings.

**Comment by kshitijSharma2014** [comment]
@Bakual  thanks for your input. :)

**Comment by javigomez** [comment]
yes sorry. Thanks @Bakual.

**Comment by puneet0191** [comment]
@javigomez Is this issue still not covered? I remember merging one PR from @kshitijSharma2014  addressing this issue

**Comment by kshitijSharma2014** [comment]
@puneet0191 let me check in the code if this test is present.
