### ISSUE TITLE
Your RSS is still not valid

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/GSOC-Webdriver_system_tests_for_CMS#80]
Still not fixing the issue:

![screen shot 2014-08-25 at 18 20 33](https://cloud.githubusercontent.com/assets/1375475/4032748/87c7fe90-2c73-11e4-89f7-f99c17d085f9.png)

As mentioned in Skype you need to provide a valid RSS. For example use: http://www.joomla.org/announcements.feed?type=rss

``` sh
JAVI:tests javiergomez$ phpunit menus/MenuItemsManager0004Test.php 
PHPUnit 3.7.29 by Sebastian Bergmann.

Configuration read from /Applications/XAMPP/xamppfiles/htdocs/testingsites/joomla-cms/tests/system/webdriver/tests/phpunit.xml.dist

.   E..

Time: 8.01 minutes, Memory: 22.75Mb

There was 1 error:

1) MenuItemsManager0004Test::addMenuItem_SingleNewsFeed_MenuItemAdded
SeleniumClient\WebDriverWaitTimeoutException: Timeout for specified condition caused by object of class: SeleniumClient\WebDriver, method invoked: findElement. Arguments: <By strategy: 'xpath', strategy factor '//a[contains(text(),'Test_Feed1638226611')]'>,<1>

/Applications/XAMPP/xamppfiles/htdocs/testingsites/joomla-cms/tests/system/webdriver/SeleniumClient/WebDriverWait.php:91
/Applications/XAMPP/xamppfiles/htdocs/testingsites/joomla-cms/tests/system/webdriver/SeleniumClient/WebDriver.php:416
/Applications/XAMPP/xamppfiles/htdocs/testingsites/joomla-cms/tests/system/webdriver/Pages/SiteContent/SiteContentFeaturedPage.php:164
/Applications/XAMPP/xamppfiles/htdocs/testingsites/joomla-cms/tests/system/webdriver/tests/menus/MenuItemsManager0004Test.php:151

FAILURES!
Tests: 4, Assertions: 268, Errors: 1.
```

cc: @kshitijSharma2014, @puneet0191

**Comment by kshitijSharma2014** [comment]
I have already fixed this issue in 
https://github.com/joomla-projects/GSOC-Webdriver_system_tests_for_CMS/pull/79

**Comment by kshitijSharma2014** [comment]
![screenshot 235](https://cloud.githubusercontent.com/assets/6698117/4041244/4a97fac2-2cf3-11e4-912c-633af9706994.png)
In here you can see that i have selected joomla connect as the news feed

![screenshot 236](https://cloud.githubusercontent.com/assets/6698117/4041248/60672f9e-2cf3-11e4-8630-567d8b7d0038.png)
Here you can see that it is getting reflected in the front end.

so I think the test is working fine but if i am wrong anywhere or your expectations are something different please let me know so that I can change my test. 

thank you

**Comment by javigomez** [comment]
I see you select the Joomla! Connect feed here: https://github.com/joomla-projects/GSOC-Webdriver_system_tests_for_CMS/pull/79/files#diff-c1cc77f92a495f15022d0ab13db1c432R123 (that already needs to be created)

Can you point me to the test were you create this feed in com_newsfeed ?

**Comment by puneet0191** [comment]
No I think, he is using an already created NewsFeed

**Comment by kshitijSharma2014** [comment]
we are running tests when the data set installed is of "learn joomla!" and this feed "joomla! connect" is already present in the administrator, so this saves our time from creating a new feed as well as we get the result what we want.

**Comment by javigomez** [comment]
okay! gotcha. Thanks.

I will proceed then with squishing the commits into one to be sent to the joomla-cms

**Comment by puneet0191** [comment]
@javigomez I agree with you, we should consider this point...while designing tests in CodeCeption
