### ISSUE TITLE
Have JoomlaWebdriverTestCase extend PHPUnit_Extensions_Selenium2TestCase

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/GSOC-Webdriver_system_tests_for_CMS#92]
Our parent test case class extends directly from the base `PHPUnit_Framework_TestCase` class.  Is there a particular reason we don't extend `PHPUnit_Extensions_Selenium2TestCase` instead?

**Comment by puneet0191** [comment]
If we try to use PHPUnit_Extensions_Selenium2TestCase instead of the current one, we might need to make changes to a lot of places, I have tried to make it extend PHPUnit_Extensions_Selenium2TestCase but it brakes the library, moreover I think It also has to do something with Nearsoft Library.
